const ALERT_ERROR = 'error';
const ALERT_WARN = 'warn';
const ALERT_SUCCESS = 'success';
const ALERT_COLORS = {
  [ALERT_ERROR]: [139, 0, 63],
  [ALERT_WARN]: [255, 205, 50],
  [ALERT_SUCCESS]: [19, 159, 114],
};
const ATTACK_INVALID = 'INVALID';
const ATTACK_PREVIOUS = 'PREVIOUS';
const ATTACK_MISS = 'MISS';
const ATTACK_HIT = 'HIT';
const ATTACK_SUNK = 'SUNK';
const VALID_ATTACK_ACTIONS = [ATTACK_HIT, ATTACK_MISS, ATTACK_SUNK];
const PLACEMENT_INVALID = 'INVALID';
const PLACEMENT_SUCCESS = 'SUCCESS';

const GAME_OPEN = 'OPEN';
const GAME_STARTED = 'STARTED';
const GAME_OVER = 'OVER';

module.exports = {
  ALERT_ERROR,
  ALERT_WARN,
  ALERT_SUCCESS,
  ALERT_COLORS,
  ATTACK_INVALID,
  ATTACK_PREVIOUS,
  ATTACK_MISS,
  ATTACK_HIT,
  ATTACK_SUNK,
  VALID_ATTACK_ACTIONS,
  GAME_OPEN,
  GAME_STARTED,
  GAME_OVER,
};
